"""
Render the README's headline tables from the committed result files, so the front page cannot drift from the data.

The README carries a block between `<!-- headline:start -->` and `<!-- headline:end -->`; this script regenerates it and
`tests/test_readme_headline.py` fails when the committed README differs from what the data says. That exists because the README once quoted
pre-Phase-2 numbers for weeks (docs/decisions.md, "corrected on the way").

    python -m scripts.render_readme_headline            # print the block
    python -m scripts.render_readme_headline --write    # update README.md in place
    python -m scripts.render_readme_headline --check    # exit 1 if README.md is out of date

Sources: reports/p3_guard_baselines.json, reports/p3_guard_hosted.json, reports/p3_action_firewall.json, reports/p3_taint_upgrade.json,
reports/redteam/*.json, reports/redteam-2026-09.md, reports/p5_pii_evaluation.json.
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
START, END = "<!-- headline:start (generated by scripts/render_readme_headline.py: edit the data, not this block) -->", "<!-- headline:end -->"


def load(rel: str):
    return json.loads((REPO / rel).read_text(encoding="utf-8"))


def pct(m: dict, kind: str) -> str:
    r = m.get(kind)
    return f"{r['rate'] * 100:.1f}%" if r else "n/a"


def cell(m: dict) -> str:
    d, f = m.get("detection"), m.get("fpr")
    if d and f:
        return f"{pct(m, 'detection')} / {pct(m, 'fpr')}"
    return pct(m, "detection") if d else pct(m, "fpr")


def detection_block() -> str:
    base, host = load("reports/p3_guard_baselines.json"), load("reports/p3_guard_hosted.json")
    ours = base["ours_ensemble"]["results"]
    pa = base["models"]["protectai/deberta-v3-base-prompt-injection-v2"]
    p22, p86 = host["models"]["Llama-Prompt-Guard-2-22M"], host["models"]["Llama-Prompt-Guard-2-86M"]
    rows = [("own_corpus", "Own corpus (78 attacks / 17 benign): detection / false-positive rate"), ("deepset_test", "deepset test (60 / 56): detection / FPR"),
            ("jbllms_clean", "jailbreak_llms not in training (244 attacks): detection"), ("jbb_benign", "JailbreakBench benign (100): FPR")]
    t = ["| Held-out set | **Ours** (rules + classifier) | ProtectAI DeBERTa | Prompt Guard 2 22M † | Prompt Guard 2 86M † | Ours OR ProtectAI |", "|---|---|---|---|---|---|"]
    for k, label in rows:
        t.append(f"| {label} | **{cell(ours[k])}** | {cell(pa['results'][k])} | {cell(p22['alone'][k])} | {cell(p86['alone'][k])} | {cell(pa['combined_with_ours'][k])} |")
    t.append(f"| Cost | **{base['ours_ensemble']['weights_on_disk_mb']:.0f} MB, about {base['ours_ensemble']['p50_latency_ms']:.1f} ms** | {pa['weights_on_disk_mb']:.0f} MB, +400 to +860 MB RAM, 70 to 830 ms (noisy) | not measured | not measured | both |")
    m = host["models"]["Llama-Prompt-Guard-2-22M"]["fpr_matched"]["rules_or_guard"]["results"]
    sh = host["shipped_default"]["results"]
    return "\n".join([
        "### Prompt-injection detection", "",
        *t, "",
        f"† Groq-hosted inference, first 1,500 characters, threshold 0.5: accuracy only. On this project's own corpus the existing guard model is the better detector ({pct(pa['results']['own_corpus'], 'detection')} vs "
        f"{pct(ours['own_corpus'], 'detection')}), and **what ships is still the from-scratch ensemble because ProtectAI does not fit the free 512 MB tier** (inferred from memory measurements, never container-tested). "
        f"Prompt Guard 2 was evaluated and rejected: at a matched false-positive budget, rules + Prompt Guard 22M finds {pct(m['deepset_test'], 'detection')} on deepset against the shipped default's {pct(sh['deepset_test'], 'detection')}. "
        "Sources: [`docs/guard-baselines.md`](docs/guard-baselines.md), [`reports/p3_guard_baselines.json`](reports/p3_guard_baselines.json), [`reports/p3_guard_hosted.json`](reports/p3_guard_hosted.json).",
    ])


def adaptive_rows() -> list[str]:
    runs = [json.loads(f.read_text(encoding="utf-8")) for f in sorted((REPO / "reports" / "redteam").glob("adaptive-*.json"))]
    all_goals = {r["goal"] for d in runs for r in d["results"]}
    rows = []
    for d in runs:
        n = len(d["results"])
        atk = (d.get("attacker_model") or d.get("model") or "").split("/")[-1]
        text = sum(bool(r["text_layers_alone_success"]) for r in d["results"])
        fw = sum(bool(r["firewall_success"]) for r in d["results"])
        rows.append((d.get("victim", "?"), atk, n, text, fw))
    order = {"robust": 0, "naive": 1, "compromised": 2}
    rows.sort(key=lambda r: (order.get(r[0], 9), r[1]))
    # a run that stopped early (free-tier token quota) says so instead of looking like a full run
    return [f"| Adaptive LLM attacker, {v} victim ({a}, {f'{n} of {len(all_goals)} goals; quota ran out' if n < len(all_goals) else f'{n} goals'}) | text layers alone {t} of {n}; with the firewall **{fw} of {n}** |"
            for v, a, n, t, fw in rows]


def firewall_block() -> str:
    fw = load("reports/p3_action_firewall.json")["summary"]
    ti = load("reports/p3_taint_upgrade.json")
    tb = load("reports/p3_taint_upgrade_before.json")
    inscope = fw["harmful_excluding_known_evasions"]
    n_in = sum(inscope.values())
    stopped = inscope.get("stopped_policy", 0) + inscope.get("stopped_taint", 0)
    mut = ti["mutation"]
    effects = list(mut["effects"].values())
    policy_goals = ("tool_scope_escalation", "cross_user", "schema_abuse")
    policy_cases = sum(mut["summary"][g]["cases"] for g in policy_goals)
    policy_bypass = sum(mut["summary"][g]["bypass"] for g in policy_goals)
    ho, hob = ti["holdout"]["caught_by_family"], tb["holdout"]["caught_by_family"]
    denied = lambda h: sum(int(v.split("/")[0]) for v in h.values())  # noqa: E731
    total = sum(int(v.split("/")[1]) for v in ho.values())
    t = ["| Test | Result |", "|---|---|",
         f"| {fw['scenarios']}-scenario agentic corpus ({fw['harmful_scenarios']} harmful, {fw['benign_scenarios']} benign) | **{stopped} of {n_in}** in-scope harmful scenarios stopped outright ({inscope.get('stopped_policy', 0)} by policy, {inscope.get('stopped_taint', 0)} by taint), {inscope.get('held_for_approval', 0)} held for approval; "
         f"{fw['known_evasion_scenarios'].get('held_for_approval', 0)} known evasions held for approval; **{len(fw['benign_false_blocks'])} benign false blocks** |",
         f"| {len(effects)} mutated calls (deterministic attacker) | {sum(e == 'deny' for e in effects)} denied, {sum(e == 'require_approval' for e in effects)} held for approval, **{sum(e in ('allow', 'executed') for e in effects)} executed**; policy-enforced goals: {policy_bypass} of {policy_cases} bypassed |",
         f"| Fresh hold-out ({total} new cases, written after the fix was frozen) | {denied(ho)} denied (was {denied(hob)} before the taint fix) |",
         *adaptive_rows()]
    return "\n".join([
        "### Action firewall (authorizing what an agent does)", "", *t, "",
        "Held for approval is not blocked: a human decides. \"Executed: 0\" is true by construction for writes (every write needs approval) and says nothing about how often real agents are hijacked. The taint check is a string-overlap heuristic: "
        "paraphrase, translation, acronyms and confidential data from a trusted tool still reach the approval queue. Not CaMeL. Same-author test design. "
        "[`docs/action-firewall.md`](docs/action-firewall.md), [`reports/p3_taint_upgrade.json`](reports/p3_taint_upgrade.json).",
    ])


def redteam_status_counts() -> dict:
    counts = {"fixed": 0, "partial": 0, "open": 0, "open_high": 0}
    for line in (REPO / "reports" / "redteam-2026-09.md").read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\| (RT-\d+) \|", line)
        if not m or m.group(1) == "RT-13":                       # RT-13 is a measurement artefact in the harness, not a weakness
            continue
        status = line.rstrip().rstrip("|").rsplit("|", 1)[-1].strip().lower()
        if status.startswith("**largely") or status.startswith("**partly"):
            counts["partial"] += 1
        elif "fixed" in status:
            counts["fixed"] += 1
        else:
            counts["open"] += 1
            severity = line.rstrip().rstrip("|").rsplit("|", 2)[-2].strip().lower()
            counts["open_high"] += "high" in severity
    return counts


def redteam_block() -> str:
    c = redteam_status_counts()
    total_findings = c["fixed"] + c["partial"] + c["open"]
    open_note = "none of the open ones is rated High" if not c["open_high"] else f"{c['open_high']} of the open ones are rated High"
    gb, ga = load("reports/redteam/garak-base-gw-stub.json")["totals"], load("reports/redteam/garak-retest2-gw-stub.json")["totals"]
    pf = load("reports/redteam/promptfoo-summary.json")["per_provider"]
    gw = next(v for k, v in pf.items() if k.startswith("gateway"))
    direct = next(v for k, v in pf.items() if k.startswith("direct"))
    t = ["| Tool / result | |", "|---|---|",
         f"| garak 0.16.0, {gb['n']} prompts through the gateway | blocked {gb['blocked'] / gb['n']:.0%} before the fixes, {ga['blocked'] / ga['n']:.0%} after; Unicode-tag smuggling 0 of 32 blocked, then 32 of 32 |",
         f"| promptfoo 0.119.0, 35 hand-written attacks (author-written, so not comparable with garak) | {gw.get('pass', 0)} of {sum(gw.values())} pass through the gateway; {direct.get('pass', 0)} of {sum(direct.values())} against the unprotected stub |",
         f"| Findings ({total_findings}) | **{c['fixed']} fixed and retested**, {c['partial']} largely or partly fixed, {c['open']} open; {open_note} |"]
    return "\n".join([
        "### Red-team (standard scanners plus an adaptive attacker)", "", *t, "",
        "One of the fixed findings is a stored XSS in the gateway's own dashboard, and another is a rate limiter a client could reset by changing a self-chosen session id. Pentest-style report with OWASP LLM 2025 and "
        "MITRE ATLAS mapping (IDs verified against MITRE's data), retests and limitations: [`reports/redteam-2026-09.md`](reports/redteam-2026-09.md). Threat model: [`SECURITY.md`](SECURITY.md).",
    ])


def pii_block() -> str:
    r = load("reports/p5_pii_evaluation.json")
    fr, ben = r["fresh"], r["benign"]["systems"]
    n = r["benign"]["texts"]
    rows = [("regex_us", "Regex before Phase 5"), ("regex", "**Regex + Indian identifiers (default)**"), ("presidio", "Presidio + custom Indian recognizers"), ("presidio_ner", "Presidio + custom + NER")]
    t = ["| PII backend (fresh labeled set) | Structured-type F1 | Benign prompts flagged | Extra RAM |", "|---|---|---|---|"]
    for k, label in rows:
        t.append(f"| {label} | {fr[k]['micro_structured']['f1']:.2f} | {ben[k]['texts_with_any_span']} of {n:,} | {r['rss_mb'][k]:.0f} MB |")
    return "\n".join([
        "### PII (redaction, Indian identifiers, pseudonymization)", "", *t, "",
        "Aadhaar (Verhoeff checksum), PAN and Indian phone numbers are gated so order numbers are not redacted. Presidio is optional, not the default: it is not more accurate on the structured types here and its NER flags "
        "ordinary prompts. Synthetic data with the recognizers' own author, so read it with the independent Gretel check in [`docs/pii-evaluation.md`](docs/pii-evaluation.md).",
    ])


def render() -> str:
    return "\n\n".join([START, detection_block(), firewall_block(), redteam_block(), pii_block(), END])


def current_block(text: str) -> str | None:
    s, e = text.find(START), text.find(END)
    return text[s:e + len(END)] if s != -1 and e != -1 else None


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    block = render()
    if "--write" in sys.argv or "--check" in sys.argv:
        path = REPO / "README.md"
        raw = path.read_text(encoding="utf-8")
        crlf = "\r\n" in raw
        text = raw.replace("\r\n", "\n")
        cur = current_block(text)
        if cur is None:
            raise SystemExit("README.md has no headline block markers")
        if "--check" in sys.argv:
            if cur != block:
                print("README headline block is out of date: run python -m scripts.render_readme_headline --write")
                raise SystemExit(1)
            print("README headline block is current")
            return
        text = text.replace(cur, block)
        path.write_text(text.replace("\n", "\r\n") if crlf else text, encoding="utf-8", newline="")
        print("README.md headline block updated")
        return
    print(block)


if __name__ == "__main__":
    main()
